Implement JWT Refresh Token
project-rainstorm/project_rainstorm pull request #100
Opened 2020-11-13 13:09 UTC by asharron

# What was done 
- Updated our JWT library to be flask_jwt_extended since it came with refresh tokens out of the box
- Updated the login route to return an access_token and a refresh_token 
- Updated login logic to read from the app config for username and password
- Added a refresh api call method to the AuthService class
- Updated logic for logout button to delete tokens from storage instead of just sending you to the login screen
- Updated Login component to automatically try and use a refresh token to re-authenticate if one is present 

# How To Test
1. Checkout the branch on your pi 
2. Edit line 24 of __init__.py for the flask server to be 5 seconds instead of 900 (so you don't have to wait 15 min to verify the refresh logic)
```
JWT_ACCESS_TOKEN_EXPIRES=timedelta(seconds=900),  # 15 min
```
2. Start FED and BED dev servers 
3. Logout on the frontend (in case you already have an access_token stored)
4.  Login using the drop user name and password 
5. Wait 5 seconds 
6. Hit refresh 
7. You should still be logged in
8. Verify the server logs show you were unauthenticated but it automatically refreshed your access_token

![image](https://user-images.githubusercontent.com/16943263/99075389-6299ee80-2587-11eb-98e3-4c2a4302cb4a.png)

2020-11-13 15:00 UTC, WillHHippo requested changes
Small change requested, otherwise looks good.

2020-11-13 15:00 UTC, WillHHippo commented on raincloud/__init__.py
> +        JWT_REFRESH_TOKEN_EXPIRES=timedelta(seconds=2592000),  # 30 days
This should probably be like a day at most. Keeping someone logged in for 30 days doesn't seem great.

2020-11-13 15:35 UTC, count-null commented
Can you also include #86? It's the last one related to login. 

Closes #78 #87 #86

2020-11-15 16:07 UTC, count-null commented
Bug found when testing. 

Steps to reproduce:
1. Start up app from scratch
2. Launch web browser
3. Notice that content does not load

Desired behaviour: 
1. App should notice that user is not logged in and redirect to the login page

Thoughts: 
Maybe the refresh token logic is missing the initial case where the user has never logged in at all. i.e. there is no token to begin with.

2020-11-15 19:06 UTC, count-null commented
I added some commits to enable changing password. Also styled the login page a bit. Added nice alerts to indicate errors, success in the login and change password process.

2020-11-21 13:54 UTC, asharron commented on raincloud/__init__.py
> +        JWT_REFRESH_TOKEN_EXPIRES=timedelta(seconds=2592000),  # 30 days
Updated :+1:

2020-11-25 19:37 UTC, merged